---
- name: playbook to install tomcat and create a user and start tomcat
  hosts: all
  tasks:
    - name: install tomcat
      apt:
        name: tomcat9
        state: present
    - name: create a user
      user:
        name: prashanth
        password: "123456"
        home: /home/prashanth
        comment: "DevOpsEngineer"
        uid: 1090
        shell: /bin/bash
    - name: start tomcat
      service:
        name: tomcat9
        state: started
